variables:
  REGISTRY: registry.gitlab.com
  REPOSITORY: jrobsonchase/blog
  IMAGE: gutenberg
  VERSION: next

image: "${REGISTRY}/${REPOSITORY}/${IMAGE}:${VERSION}"

test:
  script:
    - gutenberg build
  except:
    - master

pages:
  script:
    - gutenberg build
  artifacts:
    paths:
      - public
  only:
    - master

