variables:
  REGISTRY: registry.gitlab.com
  REPOSITORY: jrobsonchase/blog
  IMAGE: zola
  VERSION: v0.5.0

image: "${REGISTRY}/${REPOSITORY}/${IMAGE}:${VERSION}"

test:
  script:
    - zola build
  except:
    - master

pages:
  script:
    - zola build
  artifacts:
    paths:
      - public
  only:
    - master

