image: centos:7

before_script:
  - curl -s -L https://github.com/Keats/gutenberg/releases/download/v0.4.2/gutenberg-v0.4.2-x86_64-unknown-linux-gnu.tar.gz | tar xvzf -

test:
  script:
    - ./gutenberg build
  except:
    - master

pages:
  script:
    - ./gutenberg build
  artifacts:
    paths:
      - public
  only:
    - master

