stages:
  - pages

image: nixpkgs/nix-flakes

pages:
  stage: pages
  script:
    - nix build
    - cp --no-preserve ownership,mode -Lr ./result public
  artifacts:
    paths:
      - public
  only:
    - main

