variables:
  REGISTRY: registry.gitlab.com
  REPOSITORY: jrobsonchase/zola
  VERSION: v0.14.1

stages:
  - build
  - pages

image: "${REGISTRY}/${REPOSITORY}:${VERSION}"

build stable:
  stage: build
  script:
    - zola build
  artifacts:
    paths:
      - public

build latest:
  extends: build stable
  variables:
    EXTRA_PATH: latest
  image: "${REGISTRY}/${REPOSITORY}:latest"
  allow_failure: true
  script:
    - zola build --drafts -u https://josh.robsonchase.com/${EXTRA_PATH} -o public/${EXTRA_PATH}

build next:
  extends: build latest
  image: "${REGISTRY}/${REPOSITORY}:next"
  variables:
    EXTRA_PATH: next

pages:
  script: "true"
  stage: pages
  artifacts:
    paths:
      - public
  only:
    - master

