# The URL the site will be built for
base_url = "https://josh.robsonchase.com"

title = "Josh Robson Chase"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    { name = "tags", rss = true },
]

generate_rss = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true

highlight_theme = "css"

highlight_themes_css = [
    { theme = "monokai", filename = "syntax-theme-monokai.css"},
    { theme = "OneHalfDark", filename = "syntax-theme-OneHalfDark.css"},
    { theme = "base16-ocean-dark", filename = "syntax-theme-base16-ocean-dark.css" },
    { theme = "base16-ocean-light", filename = "syntax-theme-base16-ocean-light.css" },
]

[extra]
# Put all your custom variables here
google_analytics_id = "UA-129877724-1"
